<?php

return [
    'template_path' => storage_path('app/certificates/template.pdf'),
    'html_template' => 'certificates.ict',
    'background_image' => public_path('certs/ict_bg.png'),
    'unit' => 'mm',
    'page' => [
        'width' => 297,
        'height' => 210,
    ],
    'layout' => [
        'name' => [
            'x' => 120,
            'y' => 310,
            'width' => 220,
            'size' => 28,
            'style' => 'B',
            'color' => [11, 45, 107],
            'lineHeight' => 12,
            'align' => 'L',
        ],
        'candidate_no' => [
            'x' => 120,
            'y' => 350,
            'width' => 160,
            'size' => 12,
            'style' => '',
            'color' => [55, 65, 81],
            'lineHeight' => 8,
            'align' => 'L',
        ],
        'module' => [
            'x' => 120,
            'y' => 420,
            'width' => 220,
            'size' => 14,
            'style' => '',
            'color' => [55, 65, 81],
            'lineHeight' => 10,
            'align' => 'L',
        ],
        'version' => [
            'x' => 120,
            'y' => 460,
            'width' => 120,
            'size' => 12,
            'style' => '',
            'color' => [55, 65, 81],
            'lineHeight' => 8,
            'align' => 'L',
        ],
        'date' => [
            'x' => 420,
            'y' => 520,
            'width' => 120,
            'size' => 12,
            'style' => '',
            'color' => [55, 65, 81],
            'lineHeight' => 8,
            'align' => 'L',
        ],
        'footer_date' => [
            'x' => 420,
            'y' => 780,
            'width' => 120,
            'size' => 12,
            'style' => '',
            'color' => [55, 65, 81],
            'lineHeight' => 8,
            'align' => 'L',
        ],
    ],
];
